In [48]:
import pandas as pd

In [49]:
dust = pd.read_csv('../2017/dust2017_1.csv', encoding='utf-8')
dust.head()

,지역,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,111121,중구,2017010101,0.006,1.3,0.002,0.068,77.0,63.0,서울 중구 덕수궁길 15
1,서울 중구,111121,중구,2017010102,0.006,1.4,0.002,0.066,76.0,63.0,서울 중구 덕수궁길 15
2,서울 중구,111121,중구,2017010103,0.005,1.2,0.002,0.063,73.0,57.0,서울 중구 덕수궁길 15
3,서울 중구,111121,중구,2017010104,0.005,1.1,0.002,0.053,67.0,55.0,서울 중구 덕수궁길 15
4,서울 중구,111121,중구,2017010105,0.004,1.1,0.002,0.051,66.0,54.0,서울 중구 덕수궁길 15

In [50]:
del dust['측정소코드']
del dust['SO2']
del dust['CO']
del dust['O3']
del dust['NO2']

dust.head()

      지역 측정소명        측정일시  PM10  PM25             주소
0  서울 중구   중구  2017010101  77.0  63.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017010102  76.0  63.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017010103  73.0  57.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017010104  67.0  55.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017010105  66.0  54.0  서울 중구 덕수궁길 15

In [51]:
dust.rename(columns = {'PM10': '미세먼지',
                      'PM25': '초미세먼지'}, inplace=True)
dust.head()

      지역 측정소명        측정일시  미세먼지  초미세먼지             주소
0  서울 중구   중구  2017010101  77.0   63.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017010102  76.0   63.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017010103  73.0   57.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017010104  67.0   55.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017010105  66.0   54.0  서울 중구 덕수궁길 15

In [52]:
dust.to_csv('../2017/dust1.csv', sep=',', encoding='euc-kr')

In [53]:
dust = pd.read_csv('../2017/dust2017_2.csv', encoding='utf-8')
dust.head()

,지역,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,111121,중구,2017040101,0.003,0.5,0.009,0.048,16.0,11.0,서울 중구 덕수궁길 15
1,서울 중구,111121,중구,2017040102,0.002,0.4,0.031,0.024,12.0,9.0,서울 중구 덕수궁길 15
2,서울 중구,111121,중구,2017040103,0.002,0.4,0.030,0.024,10.0,8.0,서울 중구 덕수궁길 15
3,서울 중구,111121,중구,2017040104,0.002,0.4,0.022,0.027,10.0,8.0,서울 중구 덕수궁길 15
4,서울 중구,111121,중구,2017040105,0.002,0.4,0.026,0.023,12.0,8.0,서울 중구 덕수궁길 15

In [54]:
del dust['측정소코드']
del dust['SO2']
del dust['CO']
del dust['O3']
del dust['NO2']

dust.head()

      지역 측정소명        측정일시  PM10  PM25             주소
0  서울 중구   중구  2017040101  16.0  11.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017040102  12.0   9.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017040103  10.0   8.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017040104  10.0   8.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017040105  12.0   8.0  서울 중구 덕수궁길 15

In [55]:
dust.rename(columns = {'PM10': '미세먼지',
                      'PM25': '초미세먼지'}, inplace=True)
dust.head()

      지역 측정소명        측정일시  미세먼지  초미세먼지             주소
0  서울 중구   중구  2017040101  16.0   11.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017040102  12.0    9.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017040103  10.0    8.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017040104  10.0    8.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017040105  12.0    8.0  서울 중구 덕수궁길 15

In [56]:
dust.to_csv('../2017/dust2.csv', sep=',', encoding='euc-kr')

In [58]:
dust = pd.read_csv('../2017/dust2017_3.csv', encoding='utf-8')
dust.head()

,지역,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,111121,중구,2017070101,0.002,0.4,0.048,0.014,36.0,29.0,서울 중구 덕수궁길 15
1,서울 중구,111121,중구,2017070102,0.002,0.4,0.038,0.020,35.0,30.0,서울 중구 덕수궁길 15
2,서울 중구,111121,중구,2017070103,0.002,0.5,0.031,0.023,40.0,34.0,서울 중구 덕수궁길 15
3,서울 중구,111121,중구,2017070104,0.003,0.5,0.029,0.023,46.0,35.0,서울 중구 덕수궁길 15
4,서울 중구,111121,중구,2017070105,0.004,0.5,0.023,0.027,49.0,39.0,서울 중구 덕수궁길 15

In [59]:
del dust['측정소코드']
del dust['SO2']
del dust['CO']
del dust['O3']
del dust['NO2']

dust.head()

      지역 측정소명        측정일시  PM10  PM25             주소
0  서울 중구   중구  2017070101  36.0  29.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017070102  35.0  30.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017070103  40.0  34.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017070104  46.0  35.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017070105  49.0  39.0  서울 중구 덕수궁길 15

In [60]:
dust.rename(columns = {'PM10': '미세먼지',
                      'PM25': '초미세먼지'}, inplace=True)
dust.head()

      지역 측정소명        측정일시  미세먼지  초미세먼지             주소
0  서울 중구   중구  2017070101  36.0   29.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017070102  35.0   30.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017070103  40.0   34.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017070104  46.0   35.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017070105  49.0   39.0  서울 중구 덕수궁길 15

In [61]:
dust.to_csv('../2017/dust3.csv', sep=',', encoding='euc-kr')

In [62]:
dust = pd.read_csv('../2017/dust2017_4.csv', encoding='utf-8')
dust.head()

,지역,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,111121,중구,2017100101,0.004,0.8,0.002,0.065,52.0,34.0,서울 중구 덕수궁길 15
1,서울 중구,111121,중구,2017100102,0.004,0.8,0.002,0.060,50.0,32.0,서울 중구 덕수궁길 15
2,서울 중구,111121,중구,2017100103,0.003,0.7,0.004,0.052,52.0,33.0,서울 중구 덕수궁길 15
3,서울 중구,111121,중구,2017100104,0.003,0.6,0.012,0.039,50.0,32.0,서울 중구 덕수궁길 15
4,서울 중구,111121,중구,2017100105,0.003,0.6,0.017,0.028,48.0,30.0,서울 중구 덕수궁길 15

In [63]:
del dust['측정소코드']
del dust['SO2']
del dust['CO']
del dust['O3']
del dust['NO2']

dust.head()

      지역 측정소명        측정일시  PM10  PM25             주소
0  서울 중구   중구  2017100101  52.0  34.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017100102  50.0  32.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017100103  52.0  33.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017100104  50.0  32.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017100105  48.0  30.0  서울 중구 덕수궁길 15

In [64]:
dust.rename(columns = {'PM10': '미세먼지',
                      'PM25': '초미세먼지'}, inplace=True)
dust.head()

      지역 측정소명        측정일시  미세먼지  초미세먼지             주소
0  서울 중구   중구  2017100101  52.0   34.0  서울 중구 덕수궁길 15
1  서울 중구   중구  2017100102  50.0   32.0  서울 중구 덕수궁길 15
2  서울 중구   중구  2017100103  52.0   33.0  서울 중구 덕수궁길 15
3  서울 중구   중구  2017100104  50.0   32.0  서울 중구 덕수궁길 15
4  서울 중구   중구  2017100105  48.0   30.0  서울 중구 덕수궁길 15

In [65]:
dust.to_csv('../2017/dust4.csv', sep=',', encoding='euc-kr')